using MediatR;
using WastePlatform.Application.Common.Interfaces;
using WastePlatform.Domain.Entities;
using WastePlatform.Domain.Enums;

namespace WastePlatform.Application.Reports.Commands;

/// <summary>
/// Handler that validates and prepares data for report acceptance and collection task creation.
/// The actual database persistence is handled in the controller via DbContext.
/// </summary>
public class AcceptReportAndCreateTaskCommandHandler : IRequestHandler<AcceptReportAndCreateTaskCommand, AcceptReportAndCreateTaskResult>
{
    private readonly IReportRepository _reportRepository;

    public AcceptReportAndCreateTaskCommandHandler(IReportRepository reportRepository)
    {
        _reportRepository = reportRepository;
    }

    public async Task<AcceptReportAndCreateTaskResult> Handle(AcceptReportAndCreateTaskCommand request, CancellationToken cancellationToken)
    {
        // Validate that the report exists and is in valid state
        var report = await _reportRepository.GetByIdAsync(request.ReportId);
        if (report == null)
        {
            throw new InvalidOperationException("Report not found");
        }

        if (report.Status != ReportStatus.Pending)
        {
            throw new InvalidOperationException($"Report can only be accepted if it is in Pending status. Current status: {report.Status}");
        }

        // Return validation result - controller will handle actual persistence
        return new AcceptReportAndCreateTaskResult
        {
            ReportId = request.ReportId,
            CollectionTaskId = Guid.Empty, // Will be generated by controller
            ReportStatus = ReportStatus.Accepted,
            Message = "Report validation successful. Ready for acceptance."
        };
    }
}
